### ISSUE TITLE
make plot_ci() work with formula interface?

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs#24]
In addition to:

```
plot_ci(lo, hi, m)
```

could we also have

```
plot_ci( ~ lo + hi + m, data = dataframe)
```

?
Could this be achieved by making `plot_ci()` an S3 generic with methods for `numeric` and `formula`?

**Comment by andrewpbray** [comment]
Yep, we could. If that would make it cohere with the approach in the mosaic labs and wouldn't impact non-mosaic labs, I say go for it. For the non-mosaic labs, that interface doesn't seem very intuitive to me.

**Comment by beanumber** [comment]
Not on my end!

**Comment by mine-cetinkaya-rundel** [comment]
Cool I'm closing it, thanks!
