### ISSUE TITLE
Release to CRAN?

### ISSUE THREAD

**Issue by ncarchedi** [OpenIntroStat/oilabs#34]
@andrewpbray @mine-cetinkaya-rundel Since we're using this throughout the stats courses, I think it's best if we get the package on CRAN (ideally by EOY). I can help with the process if necessary. 

Besides making it more accessible for students who want to experiment outside of the course, it will also make the documentation easier to access from within DataCamp (since all CRAN packages automatically appear on RDocumentation.org).

Thoughts on what needs to happen before it's ready for release?

**Comment by andrewpbray** [comment]
For sure, this would be good. Mine and I have a meeting tomorrow to talk
through labs, and we'll discuss how far we are away from being able to
submit (I think we're very close.
