### ISSUE TITLE
devtools::use_readme_rmd()?

### ISSUE THREAD

**Issue by rpruim** [OpenIntroStat/oilabs#37]
Or similar to provide installation instructions and example use cases.

**Comment by rpruim** [comment]
Oops.  This was meant to be in a different project.  (Working on too many things simultaneously.)  But it guess it applies here as well.  So leave it open if you like.  Or close and ignore.

**Comment by nicholasjhorton** [comment]
Thanks for adding this into the oiLabs-mosaic2 repo!

All the best,

Nick
