### ISSUE TITLE
Does this pass CRAN checks?

### ISSUE THREAD

**Issue by rpruim** [OpenIntroStat/oilabs#38]
I'm suspecting not.

**Comment by mine-cetinkaya-rundel** [comment]
It's not ready for CRAN submission yet, we're working on it. Is there a particular aspect of it that is holding you up? I plan on submitting to CRAN between mid-July and end of July, however I may be able to move up some of the work if it's blocking your progress.

**Comment by rpruim** [comment]
It doesn't have to be ready for CRAN submission to be doing CRAN checks.  I recommend running CRAN checks even on things only available via github.

In the end, I'm not sure CRAN checks would catch the issue I found, however.  I recommend (a) not putting the same data set in multiple packages, and (b) using lazy data ALWAYS.  `bdims` was causing trouble because it is exported from `openintro` but requires the use of `data(dbims)` in `oilabs`.

**Comment by mine-cetinkaya-rundel** [comment]
@rpruim I agree that it doesn't have to be ready for CRAN submission to be doing CRAN checks. What I meant is that it's currently a work in progress. 

See #39 for why we chose to not use lazy data. I will look into the `bdims` issue reported there and follow up under that issue.

**Comment by rpruim** [comment]
@mine-cetinkaya-rundel I think this can be closed (but I'll let you do it).  My issues were caused by not noticing that `bdims` is in two packages with slightly different encoding.  I thought I was getting it from `oilabs`, but didn't realize that it wasn't using lazy data, so even though it was in the front of the line on the search path, the data were being pulled from `openintro`.

Took me a while to figure it out, but I understand now how it happened.  At first I thought it was a problem with the construction of the `oilabs` package and a missing export or something.  (I'm not used to watching for data that doesn't lazy load.)
