### ISSUE TITLE
unable to install.packages("oilabs") in rstudio.cloud (R3.6.0)

### ISSUE THREAD

**Issue by jricoiii** [OpenIntroStat/oilabs#42]
receive the warning

Warning in install.packages  : 
   package 'oilabs' is not available (for R version 3.6.0)

**Comment by jricoiii** [comment]
could not load package in the RStudio either.  Same error message.  I ran across this when attempting to knit the oilabs-tidy 01_intro_to _r

**Comment by mine-cetinkaya-rundel** [comment]
@jricoiii The package is at https://github.com/OpenIntroStat/oilabs currently, though soon we will be migrating everything to https://github.com/OpenIntroStat/openintro-r-package, and the lab instructions will point to the package titled openintro.

**Comment by mine-cetinkaya-rundel** [comment]
@jricoiii oilabs-tidy has now been updated to use the openintro package as mentioned above
